#define IF 1
#define ELSE 2
#define RETURN 3
#define INT 4
#define VOID 5
#define WHILE 6
#define ID 7
#define NUM 8
#define LESS_OR_EQUAL 9
#define GREATER_OR_EQUAL 10
#define EQUAL 11
#define NOT_EQUAL 12
#define LEFT_PRNTS 13
#define RIGHT_PRNTS 14
#define LEFT_BRACKET 15
#define RIGHT_BRACKET 16
#define LEFT_BRACE 17
#define RIGHT_BRACE 18
#define ADD 19
#define SUBSTRACT 20
#define MULTIPLY 21
#define DIVIDE 22
#define MOD 23
#define LESS 24
#define GREATER 25
#define ASSIGN 26
#define SEMICOLON 27
#define COMMA 28